[global]
timeout = 120
index = https://it4it-nexus-tp-repo.swissbank.com/repository/public-lib-python-pypi/
index-url = https://it4it-nexus-tp-repo.swissbank.com/repository/public-lib-python-pypi/simple/
trusted-host = it4it-nexus-tp-repo.swissbank.com
cert = /etc/ssl/certs/ca-bundle.trust.crt

[nexus]
repository = https://it4it-nexus-tp-repo.swissbank.com/repository/public-lib-python-pypi/

[distutils]
index-servers = nexus
